### ISSUE TITLE
wallet requirement to comply with GS1 LWM std

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria#10]
Steering summary:

Review wallet criteria for sections that suggest that wallets need to adhere to GS1 LWMS in any way that goes beyond delivering credentials to VRS so they can attach them to GS1-defined messages.

---

**Role of VRS (not wallet)**
As defined in `para 2.4.2.`, VRS need to cater for GS1 LWM, not digital wallets. Hence, any reference to such a requirement should be moved out of the wallet conformance criteria and into newly developed VRS conformance criteria.

`2.4.2 OCI Credentialing Roles - VRS:`
> Provides Verification Routing Service following the GS1 Lightweight Messaging Standard (LWMS) for [PI](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/index.html#dfn-product-identifier) Verifications

Suggest to move this whole sections into Getting Started and cross-reference. See ticket: https://github.com/Open-Credentialing-Initiative/OCI-Change-Requests/issues/7

**Role of wallet = VP provision**
That said, the wording in `4.1.8 Proofs & Verifications` seems appropriate, as it talks about the provision of VP in the context of LWM.  That's all that should be asked of a wallet - to enable VRS to use GS1 LWM by providing VP in a way that is compatible.

`4.1.8 Proofs & Verifications`
> Generation and Verification of a Verifiable Presentation that proves the possession of “DSCSA ATP Credential” in the context of the GS1 Lightweight Messaging Standard Protocol.

**Conflicting criteria**
[4.1 OCI Digital Wallet Standards](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#oci-digital-wallet-standards)
> Digital Wallet Implementations SHALL adopt the following set of standards:
> Messaging Standard to exchange ATP Credentials | GS1 US Implementation Guideline for Applying the GS1 Lightweight Messaging Standard for DSCSA Verification of Returned Product Identifiers

Other notable mentions of GS1 std in wallet criteria (may not be a comprehensive list):
- [3.3 GS1 Lightweight Messaging Standard](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#gs1-lightweight-messaging-standard) (no requirement but explanation - superfluous?)
- [4.1.7 Credential Serialization & Schemas](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#credential-serialization-schemas) - seemingly superfluous elaborations and future outlook that does not seem to belong into a conformance document

**Comment by bluesteens** [comment]
4.1 applies to wallet to the degree that ATP VC needs attached. need to be more specific in table

**Comment by rceleste125** [comment]
2.4.2: Consider moving this content to Getting Started Guide. Also, address the "shall".

4.1: Address requirement to adopt GS1 US guideline - may need to identify specific sections that apply to a Wallet solution (where the credential goes).

**Comment by bluesteens** [comment]
relates to https://github.com/Open-Credentialing-Initiative/OCI-Change-Requests/issues/7
