### ISSUE TITLE
security and scalability considerations of DID methods

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria#78]
# Steering: Proposal Summary 
Expansion of existing section on securing did:web and addition of did:ethr considerations

1. This removes plagiarism in the did:web section and
2. introduces equal treatment of both DID methods by adding did:ethr security considerations

#

# Steering: Publication Summary 
`Used to present completed work to Steering for approval to publish.`
`Discuss the work that was completed in reference to the above proposal.  Include any differences from the proposal and why.`
`use [GitHub Preview](https://htmlpreview.github.io/) to show final state of documents along with pull requests (if needed).`
#

---

Detailed Description:
- PR expands on existing section on [securing did:web](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#securing-did-web) and removes plagiarizing elements
- and adds did:ethr considerations

Note: this PR builds on prior edits in https://github.com/Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria/pull/53

---

Triage:
- [x] Is Issue appropriate for OCI Architecture
- [x]  Assign Size
- [x]  Assign Priority
- [x]  Assign Label (if needed)
- [x]  OCI affected Artifacts Identified
- [ ]  Assign Triage - Artifact Version Target (v x.x.x Milestone)
- [ ]  Assign Triage - Interop Profile Version Target (v x.x.x Milestone)
- [ ]  Create sub-project (if needed)
 
Affected Parties (help determine Sunrise/Sunset):
- [ ] Trading Partners
- [ ]  Issuers
- [x]  Wallet Solutions
- [ ]  PI Verification Solutions

**Affected OCI Artifact**
    
- [ ] Schema Document
- [ ] Identity Schema
- [ ] ATP Schema
- [ ] Issuer Conformance Criteria
- [x] Wallet Conformance Criteria
- [ ] VRS Solution Conformance Criteria
- [ ] Wallet API Specification
- [ ] Governance Document
- [ ] Conformance Program
- [ ] OCI Website
- [ ] Internal Process  

**Change Category (Guides Steering Review)**

   **- Steering/Industry Review**    
- [ ] Business-Level (May affect business operations)
- [ ] OCI Governance, Policy or website feature

**- Steering/Industry Notification**
- [x] Technical-Level (Does not affect business operations)
- [ ] OCI Internal Process or Infrastructure 

Communication
- [ ] Website
- [ ]  Newsletter
- [ ]  email:
- [ ]  Other:

**Comment by rceleste125** [comment]
P&A team reviewed and accepted changes on 2023-09-21 call.
