### ISSUE TITLE
para 6.2 IT sec

### ISSUE THREAD

**Issue by bluesteens** [Open-Credentialing-Initiative/Digital-Wallet-Conformance-Criteria#8]
Steering summary:
Proposal to remove the hard requirement for a SOC Report.

---

The requirement is essentially:
_The Digital Wallet provider SHALL provide a SOC report._
See [here](https://open-credentialing-initiative.github.io/Digital-Wallet-Conformance-Criteria/latest/#information-technology-controls-and-security).

Is this within the scope of OCI to demand this report over all other alternatives? Should it not be left to customer contract negotiations, SLA etc. to specify such requirements?

I suggest to change SHALL to SHOULD if the wording was not to be changed much. (After all, the ISO requirement is also a SHOULD.) Otherwise I suggest to rework the section to be more general in its request and offer SOC only as an example.

**Comment by lleifermann** [comment]
I also agree that this should be part of product or customer negotiations - Not a requirement of the OCI as SOC concentrates a lot around the practices and rules _inside_ of a company. 

I am currently working on v3.0.0 of this specification. If we want we can already integrate this change there.

**Comment by alexcolganLD** [comment]
Agree with @bluesteens and @lleifermann, this is an SLA question not an interoperability conformance question.

**Comment by bluesteens** [comment]
**Triage:**

- [ ] Is Issue appropriate for OCI Architecture
- [ ] Assign **Size**
- [ ] Assign **Priority**
- [ ] Assign **Label** (if needed)
- [ ] OCI affected Artifacts Identified
- [ ] Assign **Triage - Artifact Version Target** (v x.x.x Milestone)
- [ ] Assign **Triage - Interop Profile Version Target** (v x.x.x Milestone)
- [ ] Create sub-project (if needed)

**Comment by rceleste125** [comment]
OCI Affected Artifact: Digital Wallet Conformance Criteria

**Comment by alexcolganLD** [comment]
Agree this seems like an SLA-level question. The criterion doesn't even specify to whom the report should be provided, which suggests that it's not an interoperability requirement.

**Comment by bluesteens** [comment]
July, 27: to be released in Digital Wallet Criteria v3.3.0,  interop profile v3.2.0
